### ISSUE TITLE
Debugging / line number information

### ISSUE THREAD

**Issue by chriseth** [powdr-org/powdr#283]
For assembly, line number and call stack information might be very useful during debugging. It should be output during witness generation when generating a witness fails, but also at other times.
Since we don't always have the concept of an explicit pc (or a unique one), it should be done in an appropriately abstract way.

At the PIL level, line number information is not much more than mapping the values of a witness column to some string. We could think of a "compressed" representation, where the previous values in repeated.

```
debug <witness column name>(x) { match x { 0..5 => "sum.rs: 23 - let x = 7;", 5..7 => "sum.rs: 23 - let y = 9;", ...
```

We could even make it more generic where we just supply the row number:
```
debug <name of debug info>(i) { match pc(i) { 0..5 => "sum.rs: 23 - let x = 7;", 5..7 => "sum.rs: 23 - let y = 9;", ...
```

At the assembly level, we could add a simple instruction, directive or comment.

What is more complicated is representing the call stack. For that, we might need some code that is executed during witness generation that accesses a dynamic data structure. For now, we could limit it to just pushing and poping numbers to/from a stack.

In assembly, this is even more tricky, since we do not have a real concept of a function call, not even a built-in concept of a jump. call and return instructions need to be manually annotated.

**Comment by chriseth** [comment]
Assembly could use
```
debug file <file_nr> <file_name>;
debug loc <file_nr> <line> <col> ...;
```
then it would be an almost literal translation.

**Comment by leonardoalt** [comment]
Is this done by https://github.com/powdr-org/powdr/pull/296 ?

**Comment by chriseth** [comment]
That's the first step. There is another PR for the profiling. But I'm not sure anymore how far we want to go.

**Comment by chriseth** [comment]
Let's close this, it does not really talk about the profiler.
