### ISSUE TITLE
Bug in tests: instruction test doesn't seem to check the witness

### ISSUE THREAD

**Issue by lvella** [powdr-org/powdr#319]
The test for a new instruction I am implementing passed, but when I run it manually and check the result with pilcom, the constraints doesn't check out.

**Comment by lvella** [comment]
It seems riscv heavy tests uses `compile_asm_string_temp()`, instead of the pilcom verifying alternative `verify_asm_string()`. I tried using `verify_asm_string()` in there, but was OOM-killed. Not sure it is worth it, as the the compiler has its own asm tests that do verify with PILCOM, so they are supposed to cover for everything.

**Comment by leonardoalt** [comment]
Done.
