### ISSUE TITLE
Rust-RISCV examples with keccak do not run

### ISSUE THREAD

**Issue by AndriianChestnykh** [powdr-org/powdr#365]
I'm trying to run a few Rust-RISCV examples according to the Readme from this [repo](https://github.com/powdr-org/powdr)
I run them by the commands like this 
**cargo run --release rust riscv/tests/riscv_data/sum.rs -o tmp -f -i 10,2,4,6**

All the examples work good from my side except this 
**cargo run --release rust riscv/tests/riscv_data/keccak/src/lib.rs -o tmp -f** 
The **lib.rs** has a **tiny_keccak** dependency and it results in a the unresolved import error

<img width="948" alt="image" src="https://github.com/powdr-org/powdr/assets/17526648/0604fc6d-d343-4086-a1db-19c47c4973f7">

I am new to Rust and may be doing something wrong, so I need an advice...

OS: macOS Ventura 13.4.1
MacBook Pro M1

**Comment by leonardoalt** [comment]
If the source is a crate and not just a single rust file, you need to pass the directory of the crate instead:

```bash
cargo run --release rust riscv/tests/riscv_data/keccak/ -o tmp -f
```

It will then resolve dependencies etc

**Comment by AndriianChestnykh** [comment]
Thanks! That worked it out!
