### ISSUE TITLE
halo2 backend

### ISSUE THREAD

**Issue by chriseth** [powdr-org/powdr#83]
from @ed255:
Using halo2 as a backend via Plaf (Plonkish Arithmetization Format)
- Use this halo2 fork https://github.com/ed255/halo2 branch feature/wip-polyexen
- Import polyexen and fill in the Plaf https://github.com/Dhole/polyexen/blob/ee65714f23f3b676d936a36d5728abe4b94a5cca/src/plaf.rs#L163-L172 with all the details of your circuit.  You will need to convert your arithmetic expressions into this type https://github.com/Dhole/polyexen/blob/ee65714f23f3b676d936a36d5728abe4b94a5cca/src/expr.rs#L31-L39 which uses BigUint for values, with PlonkVar for variables https://github.com/Dhole/polyexen/blob/ee65714f23f3b676d936a36d5728abe4b94a5cca/src/expr.rs#L62-L66
- Store the witness in https://github.com/Dhole/polyexen/blob/ee65714f23f3b676d936a36d5728abe4b94a5cca/src/plaf.rs#L20-L26
- Put the plaf and witness values in the PlafH2Circuit and then you can use all the halo2 functions that expect a circuit.  This example uses the MockProver https://github.com/ed255/polyexen-demo/blob/566dcbc7ee4636798cd86b4777aed93be5a54c64/src/main.rs#L125-L128 (I haven't tested the real prover yet, but you could use this code as reference https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/8bbb22df36bdfb0afa5e258ccf95a48d6766743f/circuit-benchmarks/src/exp_circuit.rs#L55-L117 where circuit would be the PlafH2Circuit)

**Comment by leonardoalt** [comment]
This was actually done already.
